// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8x0FIly_Ap7xXbFFyMikegSci_UsDpv8',
    appId: '1:31421075835:web:81b5dba0c0ee7d59faedde',
    messagingSenderId: '31421075835',
    projectId: 'my-projectab-4d2c8',
    authDomain: 'my-projectab-4d2c8.firebaseapp.com',
    storageBucket: 'my-projectab-4d2c8.appspot.com',
    measurementId: 'G-XF475TR408',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBwaH811JtXLSkARV5UoRRSsL3gnO-ijY',
    appId: '1:31421075835:android:bc79835711fc857bfaedde',
    messagingSenderId: '31421075835',
    projectId: 'my-projectab-4d2c8',
    storageBucket: 'my-projectab-4d2c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD1Z6kDDRxT2M3fjn0gTdP7JKUwaD8Osw',
    appId: '1:31421075835:ios:d53b902b1048077bfaedde',
    messagingSenderId: '31421075835',
    projectId: 'my-projectab-4d2c8',
    storageBucket: 'my-projectab-4d2c8.appspot.com',
    iosBundleId: 'com.example.myapp',
  );
}
